[WIP] リスト機能作る
ogidow/railstutorial pull request #67
Opened 2016-09-08 08:00 UTC by ogidow

モバイルの方で必要になったので機能追加します。
モバイル研修のためということで、APIのみ実装します。

2016-09-23 02:54 UTC, ogidow commented
## エンドポイント一覧
| メソッド | エンドポイント | 内容 |
|:-----------:|:------------:|:------------:|
| POST | /api/lists/ | リストの作成 |
| PATCH | /api/lists/:id | リストの更新 |
| DELETE | /api/lists/:id | リストの削除 |
| GET | /api/lists/:list_id/members | リストに追加されているユーザ一覧の取得 |
| POST | /api/lists/:list_id/members | リストへのユーザの追加 |
| DELETE | /api/lists/:list_id/members/:id | リストからユーザを削除
| GET | /api/lists/:id/microposts | リストのマイクロポスト一覧を取得 |

2016-09-23 09:24 UTC, ry023 commented on app/assets/javascripts/api/lists.coffee
> +# You can use CoffeeScript in this file: http://coffeescript.org/
scriptたち使ってなさそうなので消してもいいかも

2016-09-23 09:25 UTC, ry023 requested changes

2016-09-26 02:08 UTC, ry023 approved these changes

2016-09-26 02:09 UTC, shimoju commented on app/assets/stylesheets/api/lists/members.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
CSSいらないと思います

2016-09-26 02:09 UTC, ry023 commented on app/assets/stylesheets/api/lists.scss
> +// You can use Sass (SCSS) here: http://sass-lang.com/
これも消そう！

2016-09-26 02:21 UTC, shimoju commented on test/integration/api/lists_update_test.rb
> +    list_name = "enginner"
本題とは関係ないけど、engineerのスペルミスだと思います

2016-09-26 02:23 UTC, ry023 commented
LGTM

2016-09-26 02:25 UTC, shimoju commented on test/models/list_test.rb
> +  # end
インテグレーションテストで担保されてるといえるけど、簡単なレベルでいいので単体テストも書いたほうがいいかなと思いました
（テストの速度の問題と、モデルがもつ振る舞いがわかりやすくなるので）

2016-09-26 02:33 UTC, shimoju commented on test/integration/api/lists_create_test.rb
> +    params = response_json
> paramsってなんか個人的には違和感がある
> というかresponse_jsonそのまま使っても良さそうやな

とりょうさんに指摘されていたのでそのまま載せます（笑）
https://github.com/ogidow/railstutorial/pull/71#discussion_r80208566

変数が長いとしても利用している場所は1箇所だし、response_jsonを直接使った方がいいかなと思いました

2016-09-26 03:04 UTC, shimoju commented
LGTM 🙆 
おつかれさまでした

2016-09-26 03:04 UTC, merged