[WIP] フォロー・フォロワーリストのAPIを作成する
ogidow/railstutorial pull request #71
Opened 2016-09-23 09:00 UTC by shimoju

Api::UsersControllerのfollowing,followersアクションを実装します

2016-09-23 09:15 UTC, ry023 commented on test/integration/api/following_test.rb
> +    assert_equal params[:errors][:followed_id], ["has already been taken"]
paramsってなんか個人的には違和感がある
というかresponse_jsonそのまま使っても良さそうやな

2016-09-23 09:19 UTC, ry023 requested changes

2016-09-26 05:37 UTC, ogidow commented
LGTM 🙆

2016-09-26 05:38 UTC, ry023 approved these changes

2016-09-26 05:40 UTC, ry023 commented
LGTM

2016-09-26 05:40 UTC, merged